SELECT
    b.AUTHOR_ID,
    AUTHOR_NAME,
    b.CATEGORY,
    SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK b
    JOIN AUTHOR ON b.AUTHOR_ID = AUTHOR.AUTHOR_ID
    JOIN BOOK_SALES ON b.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY b.AUTHOR_ID,
         b.CATEGORY
ORDER BY b.AUTHOR_ID ASC,
         CATEGORY DESC